# Generated by Django 5.2.5 on 2025-08-28 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_voyage', models.CharField(choices=[('ETUDES', 'Études'), ('TRAVAIL', 'Travail'), ('TOURISME', 'Tourisme'), ('PELERINAGE', 'Pèlerinage')], max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='en_cours', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='core.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('PASSEPORT', 'Passeport'), ('VISA', 'Visa'), ('BILLET', 'Billet'), ('ASSURANCE', 'Assurance')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='travel.dossiervoyage')),
            ],
        ),
    ]
