# Generated by Django 5.2.6 on 2025-10-03 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_address_profile_bio_profile_city_and_more'),
        ('travel', '0002_country_travelbooking_passenger_bookingstatushistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('from_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro'), ('CAD', 'Dollar canadien'), ('GBP', 'Livre sterling'), ('CHF', 'Franc suisse'), ('JPY', 'Yen japonais'), ('CNY', 'Yuan chinois'), ('NGN', 'Naira nigérian'), ('GHS', 'Cedi ghanéen'), ('ZAR', 'Rand sud-africain')], max_length=3, verbose_name='Devise à échanger')),
                ('to_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro'), ('CAD', 'Dollar canadien'), ('GBP', 'Livre sterling'), ('CHF', 'Franc suisse'), ('JPY', 'Yen japonais'), ('CNY', 'Yuan chinois'), ('NGN', 'Naira nigérian'), ('GHS', 'Cedi ghanéen'), ('ZAR', 'Rand sud-africain')], max_length=3, verbose_name='Devise à recevoir')),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant à envoyer')),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Taux appliqué')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frais')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant net à recevoir')),
                ('reception_method', models.CharField(choices=[('agency_pickup', 'Retrait en agence'), ('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Mode de réception')),
                ('pickup_agency', models.CharField(blank=True, max_length=100, verbose_name='Agence de retrait')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, verbose_name='Titulaire du compte')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN/RIB')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('mobile_operator', models.CharField(blank=True, max_length=50, verbose_name='Opérateur mobile')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro mobile')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('rejected', 'Refusé')], default='pending', max_length=20, verbose_name='Statut')),
                ('client_notes', models.TextField(blank=True, verbose_name='Notes client')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'exécution")),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='exchange_receipts/', verbose_name='Reçu PDF')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exchanges', to=settings.AUTH_USER_MODEL, verbose_name='Agent assigné')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchanges', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': "Demande d'échange de devise",
                'verbose_name_plural': "Demandes d'échange de devise",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro'), ('CAD', 'Dollar canadien'), ('GBP', 'Livre sterling'), ('CHF', 'Franc suisse'), ('JPY', 'Yen japonais'), ('CNY', 'Yuan chinois'), ('NGN', 'Naira nigérian'), ('GHS', 'Cedi ghanéen'), ('ZAR', 'Rand sud-africain')], max_length=3, verbose_name='Devise source')),
                ('to_currency', models.CharField(choices=[('XAF', 'Franc CFA'), ('USD', 'Dollar américain'), ('EUR', 'Euro'), ('CAD', 'Dollar canadien'), ('GBP', 'Livre sterling'), ('CHF', 'Franc suisse'), ('JPY', 'Yen japonais'), ('CNY', 'Yuan chinois'), ('NGN', 'Naira nigérian'), ('GHS', 'Cedi ghanéen'), ('ZAR', 'Rand sud-africain')], max_length=3, verbose_name='Devise cible')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Taux de change')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Frais (%)')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais fixe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Valide depuis')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'à")),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-valid_from'],
                'unique_together': {('from_currency', 'to_currency', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Créé'), ('submitted', 'Soumis'), ('status_changed', 'Statut modifié'), ('assigned', 'Assigné à un agent'), ('completed', 'Effectué'), ('cancelled', 'Annulé'), ('rejected', 'Refusé'), ('notes_added', 'Notes ajoutées')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='travel.currencyexchangerequest')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'échange",
                'verbose_name_plural': "Historiques d'échange",
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('exchange_status', "Changement de statut d'échange"), ('exchange_completed', 'Échange terminé'), ('appointment_reminder', 'Rappel de rendez-vous'), ('document_required', 'Document requis'), ('general', 'Général')], default='general', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='travel.appointment', verbose_name='Rendez-vous lié')),
                ('related_exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='travel.currencyexchangerequest', verbose_name='Échange lié')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.client', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
