# Generated by Django 5.2.5 on 2025-08-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('type_piece', models.CharField(help_text="Type de pièce d'identité", max_length=50)),
                ('numero_piece', models.CharField(max_length=50, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('pays', models.CharField(default='Cameroun', max_length=50)),
            ],
        ),
    ]
